In [37]:
# previously recorded values from the reconnaissance run of dcraw
black = 2044
white = 16383
r_scale = 2.165039
g_scale = 1.0
b_scale = 1.643555

## python initials
here, we use skimage's imread to get read the image and obtain values

In [38]:
import numpy as np
from skimage.io import imread

image = imread("../../../data/Thayer.tiff").astype(np.float32)
print("height, width:", image.shape, "as type", image.dtype)
print("bits per pixel:", image.itemsize * 8)

height, width: (4016, 6020) as type float32
bits per pixel: 32


we can then convert this image into a double-precision array

In [39]:
image = image.astype(np.float64)
print("bits per pixel:", image.itemsize * 8)

bits per pixel: 64


## linearization
we can apply a linear transformation to the image so that the value \<black> is mapped to 0, and the value \<white> is mapped to 1. we then clip the negative values to 0, and values greater than 1 to 1

In [40]:
print(image)
print("original min/max value:", image.min(), image.max())

image = (image - (black)) / (white - black)     # shift min to 0
print("post transformation min/max value:", image.min(), image.max())

image = np.clip(image, 0, 1)  # clip to [0, 1]
print("post clip min/max value:", image.min(), image.max())
print(image)

[[3429. 6292. 3911. ... 6738. 3028. 5556.]
 [6061. 5622. 7062. ... 5356. 6064. 5850.]
 [3386. 6240. 3714. ... 6249. 3473. 6036.]
 ...
 [2443. 2300. 2333. ... 2278. 2343. 2269.]
 [2246. 2400. 2189. ... 2206. 2061. 2186.]
 [2154. 2237. 2178. ... 2443. 2119. 2291.]]
original min/max value: 255.0 15305.0
post transformation min/max value: -0.12476462793779204 0.9248204198340191
post clip min/max value: 0.0 0.9248204198340191
[[0.09658972 0.29625497 0.13020434 ... 0.32735895 0.06862403 0.24492642]
 [0.28014506 0.24952926 0.34995467 ... 0.23097845 0.28035428 0.26542995]
 [0.09359091 0.2926285  0.11646558 ... 0.29325615 0.09965827 0.27840156]
 ...
 [0.02782621 0.01785341 0.02015482 ... 0.01631913 0.02085222 0.01569147]
 [0.01408745 0.02482739 0.01011228 ... 0.01129786 0.00118558 0.00990306]
 [0.00767139 0.01345979 0.00934514 ... 0.02782621 0.00523049 0.01722575]]
